# Generated by Django 6.0 on 2026-06-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_type_id', models.IntegerField(default=0)),
                ('choice_name', models.CharField(max_length=200)),
            ],
        ),
    ]
