# Generated by Django 6.0 on 2026-06-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_idea_generator', '0002_option_delete_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_type',
            field=models.IntegerField(choices=[(1, 'Interest'), (2, 'Tech'), (3, 'Goal')], default=3),
        ),
    ]
