# Generated by Django 6.0 on 2026-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_idea_generator', '0003_alter_option_option_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
    ]
